### ISSUE TITLE
Find out which side of the robot is "front". Adjust auto code for this

### ISSUE THREAD

**Issue by cowanwalls** [Team708/2015-Banshee#24]
Currently claw and indexer auto code reference positive distances. Note that the encoder reads both positive and negative distances, so this method DOES NOT WORK. We need to know what the drivers would consider the front of the robot, but before then we still need to standardize. We can change the standard later but we need a standard to test auto. This is important. This will be a topic of discussion over the weekend while we wait for the robot.

**Comment by omn0mn0m** [comment]
I would consider the indexer as the front, and the claw as the back. Adjust accordingly.

**Comment by omn0mn0m** [comment]
I think what we want to do is consider the indexer as the front, and the claw as the back.
